/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/room.glb')
  return (
    <group 
      {...props} 
      dispose={null}
      scale={[3, 3, 3]} // Adjusted scale to be smaller
      position={[0, -0.5, 0]} // Slightly lower position
      rotation={[0, 6 , 0]} // Gentle rotation
    >
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={nodes.mesh_0.material} 
      />
    </group>
  )
}

useGLTF.preload('/models/room.glb')
